# Generated by Django 5.0.4 on 2024-06-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllRecipes', '0002_remove_user_followers_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Recipe',
        ),
    ]
