# Generated by Django 5.0.4 on 2024-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yummly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Yummy',
        ),
    ]
